name: Build and deploy Jekyll site

on:
  push:
    branches:
      - jekyll

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy Custom Config
        run: |
          cp v4/_config.yml _config.yml
          cp -rf v4/_layouts _layouts
          cp -rf v4/assets assets

      - name: List Files for Debugging
        run: ls -R

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Jekyll and Bundler
        run: gem install bundler jekyll minima

      - name: Build Jekyll Site
        run: jekyll build

      - name: List Files for Debugging
        run: ls /home/runner/work/caioaamaral.github.io/caioaamaral.github.io/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
